"""L2 scaffold package: ScaffoldSpec registry + builders."""
from namepredict.layer2.scaffold.specs import (
    BENZODIAZINE_SPECS,
    CARBOCYCLE_SPECS,
    FUSED56_LABELS,
    FUSED56_SPECS,
    MONO_CARBO_SPECS,
    MONO_HETERO_SPECS,
    NAPH_FAMILY_SPECS,
    NAPH_LABELS,
    POLY_CARBO_SPECS,
    NumberingPolicy,
    ScaffoldSpec,
    all_specs,
    fused56_kind_ids,
    get_spec,
    kind_ids_for,
    monohetero_kind_ids,
    naph_kind_ids,
)

__all__ = [
    "BENZODIAZINE_SPECS",
    "CARBOCYCLE_SPECS",
    "FUSED56_LABELS",
    "FUSED56_SPECS",
    "MONO_CARBO_SPECS",
    "MONO_HETERO_SPECS",
    "NAPH_FAMILY_SPECS",
    "NAPH_LABELS",
    "POLY_CARBO_SPECS",
    "NumberingPolicy",
    "ScaffoldSpec",
    "all_specs",
    "fused56_kind_ids",
    "get_spec",
    "kind_ids_for",
    "monohetero_kind_ids",
    "naph_kind_ids",
]
